version: '3.8'
services:
  db:
    restart: on-failure
    image: postgres:latest
    container_name: postgresDb
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=toplearn
      - POSTGRES_PASSWORD=postgres
    networks:
      - toplearn_network
  redis:
    restart: on-failure
    image: redis:latest
    ports:
      - '6377:6379'
    environment:
      - REDIS_PORT=6739

networks:
  toplearn_network: {}
